define({
  root: ({
    "_widgetLabel": "TranslatableOutput",
    "label1": "movie",
    "label2": "charity",
    "label3": "birthday",
    "label4": "property",
    "label5": "series",
    "label6": "chest",
    "label7": "loss",
    "label8": "girl",
    "label9": "selection",
    "label10": "night",
    "label11": "stranger",
    "label12": "mode",
    "label13": "supermarket",
    "label14": "ear",
    "label15": "blood",
    "label16": "tale",
    "label17": "revolution",
    "label18": "news",
    "label19": "criticism",
    "label20": "temperature",
  }),
  "de": 1
});
